# CREDENTIALS CONFIG
LD_CREDS_FILE_NAME = 'YOUR_LD_CREDS_FILE.json'
LD_CREDS_PATH = f'/tmp/{LD_CREDS_FILE_NAME}'
TWILIO_CREDS_FILE_NAME = 'YOUR_TWILIO_CREDS_FILE.json'
TWILIO_CREDS_PATH = f'/tmp/{TWILIO_CREDS_FILE_NAME}'

# ONCALL CONFIG
ONCALL = 'ONCALL_NAME_HERE'
FROM_NUMBER = 'YOUR_TWILIO_SMS_NUMBER_HERE'
TO_NUMBER = 'ONCALL_NUMBER_HERE'
